services:
  - type: web
    name: pipeheal-backend
    env: node
    buildCommand: "cd backend && npm install && npm run build"
    startCommand: "cd backend && npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false

  - type: redis
    name: pipeheal-redis
    ipAllowList: [] # only allow internal connections
    plan: free
