import incidentRepo from '../repositories/incident.repository.js';
import { activityRepository } from '../repositories/sandbox.repository.js';
import { ApiError } from '../utils/ApiError.js';
import ERROR_CODES from '../constants/errorCodes.js';

export const incidentService = {
  async listIncidents(filters = {}) {
    return incidentRepo.findAll(filters);
  },

  async getIncident(id, userId = null) {
    const incident = await incidentRepo.findById(id);
    if (!incident) throw new ApiError(404, 'Incident not found', ERROR_CODES.NOT_FOUND);
    // Ownership check: if userId provided, verify the incident belongs to their repository
    if (userId && incident.repository?.userId !== userId) {
      throw new ApiError(404, 'Incident not found', ERROR_CODES.NOT_FOUND);
    }
    return incident;
  },

  async createIncident(data, userId) {
    const incident = await incidentRepo.create(data);
    
    await activityRepository.create({
      eventType: 'incident_created',
      title: 'Incident Created',
      description: `Incident "${data.title}" was opened.`,
      incidentId: incident.id,
      userId,
    });

    return incident;
  },

  async updateIncident(id, data, userId) {
    const incident = await incidentRepo.findById(id);
    if (!incident) throw new ApiError(404, 'Incident not found', ERROR_CODES.NOT_FOUND);
    // Ownership check when userId is provided
    if (userId && userId !== 'system' && incident.repository?.userId !== userId) {
      throw new ApiError(404, 'Incident not found', ERROR_CODES.NOT_FOUND);
    }

    const updated = await incidentRepo.update(id, data);

    if (data.status && data.status !== incident.status) {
      await activityRepository.create({
        eventType: 'incident_updated',
        title: 'Status Changed',
        description: `Status changed from ${incident.status} to ${data.status}`,
        incidentId: id,
        userId,
      });
    }

    return updated;
  },

  async generatePatchAndPR(incidentId, userId, token, filePath = '.github/workflows/pipeheal-test.yml') {
    const { db } = await import('../config/prisma.js');
    const githubService = (await import('./github.service.js')).default;
    const aiService = (await import('./ai.service.js')).default;
    const validationService = (await import('./validation.service.js')).default;

    const incident = await this.getIncident(incidentId);
    if (!incident) throw new ApiError(404, 'Incident not found');

    const repoName = incident.repository?.name;
    const ownerName = incident.repository?.owner;
    if (!repoName || !ownerName) throw new ApiError(400, 'Repository not found for incident');

    const originalFile = await githubService.getFile(ownerName, repoName, filePath, token);
    
    const diagnosisText = incident.rootCause || incident.title;

    // RAG: Fetch similar successful fixes from the Knowledge Base
    const knowledgeBaseService = (await import('./knowledgeBase.service.js')).default;
    const similarFixes = await knowledgeBaseService.findSimilarFixes(incident.repositoryId, diagnosisText);

    const patchResult = await aiService.generatePatch(diagnosisText, filePath, originalFile.content, similarFixes);
    
    const validation = await validationService.validatePatch(
      ownerName, repoName, filePath, patchResult.patchedCode, token
    );

    const patchRecord = await db.patch.create({
      data: {
        filePath,
        originalCode: originalFile.content,
        patchedCode: patchResult.patchedCode,
        diff: patchResult.diff,
        description: patchResult.description,
        aiModel: aiService.getProvider(),
        status: validation.success ? 'VERIFIED' : 'REJECTED',
        incidentId
      }
    });

    if (!validation.success) {
      await this.updateIncident(incidentId, { status: 'OPEN' }, userId);
      throw new ApiError(400, 'Patch validation failed. Check incident details.');
    }

    const branchName = `pipeheal-fix-${incidentId}-${Date.now()}`;
    await githubService.createBranch(ownerName, repoName, branchName, 'main', token);
    await githubService.commitFile(
      ownerName, repoName, filePath, 
      `fix: ${patchResult.description || 'AI Auto-Fix'}`, 
      patchResult.patchedCode, branchName, token, originalFile.sha
    );

    const pr = await githubService.createDraftPR(
      ownerName, repoName, 
      `AI Auto-Fix: ${incident.title}`, 
      `Generated by PipeHeal AI.\n\nDescription: ${patchResult.description}\n\nValidation Logs:\n\`\`\`\n${validation.logs}\n\`\`\``, 
      branchName, 'main', token
    );

    await db.pullRequest.create({
      data: {
        title: pr.title,
        body: pr.body,
        headBranch: branchName,
        baseBranch: 'main',
        htmlUrl: pr.html_url,
        state: 'draft',
        incidentId
      }
    });

    // RAG: Add this successful patch to the Knowledge Base!
    await knowledgeBaseService.addEntry(
      incident.repositoryId,
      diagnosisText,
      patchResult.description,
      patchResult.diff
    );

    await this.updateIncident(incidentId, {
      status: 'RESOLVED',
      resolvedAt: new Date()
    }, userId);

    return { prUrl: pr.html_url, logs: validation.logs };
  }
};

export default incidentService;
