/**
 * Standardized API error codes.
 * Used across controllers, services, and middleware.
 */

export const ERROR_CODES = {
  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  OAUTH_FAILED: 'OAUTH_FAILED',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',

  // Resources
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  CONFLICT: 'CONFLICT',

  // Server
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  BAD_GATEWAY: 'BAD_GATEWAY',
  TIMEOUT: 'TIMEOUT',

  // Database
  DB_ERROR: 'DB_ERROR',
  DB_UNAVAILABLE: 'DB_UNAVAILABLE',

  // GitHub
  GITHUB_NOT_CONFIGURED: 'GITHUB_NOT_CONFIGURED',
  GITHUB_API_ERROR: 'GITHUB_API_ERROR',
  WEBHOOK_INVALID: 'WEBHOOK_INVALID',

  // AI
  AI_NOT_CONFIGURED: 'AI_NOT_CONFIGURED',
  AI_ANALYSIS_FAILED: 'AI_ANALYSIS_FAILED',

  // Docker
  DOCKER_NOT_AVAILABLE: 'DOCKER_NOT_AVAILABLE',
  SANDBOX_FAILED: 'SANDBOX_FAILED',
  SANDBOX_TIMEOUT: 'SANDBOX_TIMEOUT',
};

export default ERROR_CODES;
